# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x]
        pnpm: ["6.9.0"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Use PNPM ${{ matrix.pnpm }}
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ matrix.pnpm }}
      - name: Set PNPM StoreDir
        run: pnpm config set store-dir ~/.pnpm-store
      - name: Cache PNPM modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-
      - name: Install packages
        run: pnpm install
      - name: Run linter and tests
        run: pnpm run test
      - name: Export coverage report
        run: pnpm run tap:coverage -- --coverage-report=lcovonly
      - name: Upload report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage/lcov.info
